In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:95% !important;}
div.cell.code_cell.rendered{width:95%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:22pt;}
.inner_cell{font-size:22pt;}
div.text_cell_render pre code {font-size:22pt; line-height:30px;}
div.output {font-size:20pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:22pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:20pt;padding:5px;}
table.dataframe{font-size:22px;}
</style>
"""))

In [1]:
import pandas as pd # 파일입력(read_excel), 교차표(crosstab), 원핫인코딩(get_dummies)
import numpy as np
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split # 훈련셋과 시험셋 분리 함수
from tensorflow.keras.utils import to_categorical # 원핫인코딩
from tensorflow.keras.models import Sequential, save_model, load_model
# 과적합을 줄이기 위한 방법 : dropout, 배치정규화, L2정규화
from tensorflow.keras.layers import Dense, Input, Dropout, BatchNormalization
from tensorflow.keras.regularizers import l2
# 데이터 불균형 극복 5.5 : 4.5 => 5:5
from sklearn.utils.class_weight import compute_class_weight
import matplotlib.pyplot as plt # 모델 학습과정 살펴보기
from sklearn.metrics import confusion_matrix # 혼동행렬

```
age: 나이 (년 단위)
sex: 성별 (1 = 남성, 0 = 여성)
cp (Chest Pain Type): 흉통의 유형 (0~3 값, 일반 협심증부터 무증상까지 분류)
trestbps: 안정 시 혈압 (mmHg)
chol: 혈청 콜레스테롤 수치 (mg/dl)
fbs (Fasting Blood Sugar): 공복 혈당이 120 mg/dl 초과인지 여부 (1 = 참, 0 = 거짓)
restecg: 안정 시 심전도(ECG) 결과 (0~2)
thalach: 운동 시 달성한 최대 심박수
exang: 운동 유발 협심증 여부 (1 = 있음, 0 = 없음)
oldpeak: 휴식기에 비해 운동 시 나타나는 ST 부위 하강(ST depression) 정도
slope: 최고 운동 시 ST 세그먼트의 기울기ca: 형광투시법으로 색칠된 주요 혈관 수 (0~3개)
thal: 지중해빈혈 등 혈액 질환 여부 (정상, 고정 결함, 가역적 결함 등)
target (Diagnosis): 심장질환 진단 결과 (0 = 정상, 1 = 심장질환 있음)
```

# 이진분류(로지스틱 회귀분석)
- 1. 데이터셋 생성 & 전처리
    * 엑셀 -> 데이터프레임 -> ?처리(결측치로 전환하여 결측치처리) -> X, y분리
        -> X변수의 scale조정 -> train_test_split()을 이용하여 학습셋과 테스트셋을 분리
- 2. 모델 생성(입력13,타겟1) - 과적합 고려 & 학습과정설정 & 학습
- 3. 모델 평가(그래프, 평가, 혼동행렬=교차표)
- 4. 모델 사용

## 1. 데이터셋 생성 & 전처리

In [2]:
df = pd.read_excel('data/heart-disease.xlsx',
                  # sheet_name='processed.cleveland'
                  )
df.head()

,age,sex,cp,treshtbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,hsl,heartDisease
0,63,1,1,145,233,1,2,150,0,2.3,3,0,6,0
1,67,1,4,160,286,0,0,108,1,1.5,2,3,3,1
2,67,1,4,120,?,0,2,129,1,2.6,2,2,7,1
3,37,1,3,130,250,0,0,187,0,3.5,3,0,3,0
4,41,0,2,130,204,0,2,172,0,1.4,1,0,3,0

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   age           303 non-null    int64
 1   sex           303 non-null    int64
 2   cp            303 non-null    int64
 3   treshtbps     303 non-null    int64
 4   chol          303 non-null    object
 5   fbs           303 non-null    int64
 6   restecg       303 non-null    int64
 7   thalach       303 non-null    int64
 8   exang         303 non-null    int64
 9   oldpeak       303 non-null    float64
 10  slope         303 non-null    int64
 11  ca            303 non-null    object
 12  hsl           303 non-null    object
 13  heartDisease  303 non-null    int64
dtypes: float64(1), int64(10), object(3)
memory usage: 33.3+ KB

In [12]:
df.isnull().sum()

age             0
sex             0
cp              0
treshtbps       0
chol            0
fbs             0
restecg         0
thalach         0
exang           0
oldpeak         0
slope           0
ca              0
hsl             0
heartDisease    0
dtype: int64

In [14]:
df.isin(['?']).sum()

age             0
sex             0
cp              0
treshtbps       0
chol            1
fbs             0
restecg         0
thalach         0
exang           0
oldpeak         0
slope           0
ca              4
hsl             2
heartDisease    0
dtype: int64

In [5]:
df[(df['chol']=='?') | (df['ca']=='?') | (df['hsl']=='?') ]

     age  ...  heartDisease
2     67  ...             1
87    53  ...             0
166   52  ...             0
192   43  ...             1
266   52  ...             1
287   58  ...             0
302   38  ...             0

[7 rows x 14 columns]

In [3]:
# 방법1 : ?가 있는 행을 삭제
drop_idx = df[(df['chol']=='?') | (df['ca']=='?') | (df['hsl']=='?') ].index # 삭제할 행
df = df.drop(drop_idx)

In [9]:
# 방법2:?를 결측치로 대체 => 결측치 삭제
df = df.replace('?', np.nan)
df[(df['chol']=='?') | (df['ca']=='?') | (df['hsl']=='?') ]

Empty DataFrame
Columns: [age, sex, cp, treshtbps, chol, fbs, restecg, thalach, exang, oldpeak, slope, ca, hsl, heartDisease]
Index: []

In [27]:
# 결측치가 포함된 데이터 추출
df[df['chol'].isna() | df['ca'].isna() | df['hsl'].isna()]
df[df.isna().any(axis=1)]

     age  ...  heartDisease
2     67  ...             1
87    53  ...             0
166   52  ...             0
192   43  ...             1
266   52  ...             1
287   58  ...             0
302   38  ...             0

[7 rows x 14 columns]

In [31]:
# 결측치 처리 : 삭제(dropna) cf. fillna() apply()
df.dropna(how='any', inplace=True) # 결측치가 한열이라도 있으면 삭제
df[df.isna().any(axis=1)]

Empty DataFrame
Columns: [age, sex, cp, treshtbps, chol, fbs, restecg, thalach, exang, oldpeak, slope, ca, hsl, heartDisease]
Index: []

In [10]:
df.isna().sum()

age             0
sex             0
cp              0
treshtbps       0
chol            0
fbs             0
restecg         0
thalach         0
exang           0
oldpeak         0
slope           0
ca              0
hsl             0
heartDisease    0
dtype: int64

In [11]:
df.shape

(296, 14)

In [12]:
# 타겟변수 분포가 균형적인지
df['heartDisease'].value_counts()/df.shape[0]

0    0.540541
1    0.459459
Name: heartDisease, dtype: float64

In [13]:
df['heartDisease'].value_counts(normalize=True)

0    0.540541
1    0.459459
Name: heartDisease, dtype: float64

In [4]:
# X, y분리
X = df.iloc[:, :-1].values # 맨마지막 열을 제외한 부분을 numpy배열
y = df.iloc[:, -1:].to_numpy() # 2차원 numpy 배열
X.shape, y.shape

((296, 13), (296, 1))

In [5]:
# X변수의 scale조정
scaler = MinMaxScaler()
scaled_X = scaler.fit_transform(X)
print('원 데이터 :', X[0])
print('스케일 조정 데이터 :', scaled_X[0])

원 데이터 : [63 1 1 145 233 1 2 150 0 2.3 3 0 6]
스케일 조정 데이터 : [0.70833333 1.         0.         0.48113208 0.24429224 1.
 1.         0.60305344 0.         0.37096774 1.         0.
 0.75      ]

In [6]:
# scaled_X와 y를 학습데이터셋:테스트셋 = 8:2
X_train, X_test, y_train, y_test = train_test_split(scaled_X,
                                    y,
                                    #train_size=0.8,
                                    test_size=0.2,
                                    random_state=7, # seed값
                                    stratify=y) # 층화추출

In [17]:
# 심장병 음성/양성 비율(y, y_train, y_test)
print(pd.DataFrame(y).value_counts(normalize=True))
print(pd.DataFrame(y_train).value_counts(normalize=True))
print(pd.DataFrame(y_test).value_counts(normalize=True))

0    0.540541
1    0.459459
dtype: float64
0    0.542373
1    0.457627
dtype: float64
0    0.533333
1    0.466667
dtype: float64

In [7]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((236, 13), (236, 1), (60, 13), (60, 1))

## 2. 모델생성 & 학습과정 설정 & 학습
- 모델 : 13 -> 32 -> 16 -> 8 -> 1
- 학습과정을 시각화한 그래프를 보고 과적합 줄이기
- 과적합 줄이기 위한 방법

In [9]:
model = Sequential(name='sequential')
model.add(Dense(units=32, input_dim=13, activation='relu'))
model.add(Dense(units=16, activation='relu'))
model.add(Dense(units=8, activation='relu'))
model.add(Dense(units=1, activation='sigmoid'))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_4 (Dense)             (None, 32)                448

 dense_5 (Dense)             (None, 16)                528

 dense_6 (Dense)             (None, 8)                 136

 dense_7 (Dense)             (None, 1)                 9

=================================================================
Total params: 1,121
Trainable params: 1,121
Non-trainable params: 0
_________________________________________________________________

In [12]:
# 학습과정 설정
from tensorflow.keras.metrics import Recall, Precision, Accuracy
from tensorflow.keras.optimizers import Adam
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              # optimizer=Adam(learning_rate=0.001),
              metrics=['accuracy', #Accuracy(name='accuracy'), 
                       Recall(name='recall'),        # 재현율(실제값 중심=1을 얼마나 잘 예측했는지)
                       Precision(name='precision')]) # 정밀도(예측값 중심=1이라고 예측한 것 중 얼마나 1인지)

In [13]:
# 학습
hist = model.fit(X_train, y_train, # 학습데이터
                epochs=200, # 학습횟수
                verbose=2)

Epoch 1/200
8/8 - 2s - loss: 0.6951 - accuracy: 0.5212 - recall: 0.6667 - precision: 0.4832 - 2s/epoch - 288ms/step
Epoch 2/200
8/8 - 0s - loss: 0.6810 - accuracy: 0.5763 - recall: 0.7407 - precision: 0.5263 - 47ms/epoch - 6ms/step
Epoch 3/200
8/8 - 0s - loss: 0.6677 - accuracy: 0.6229 - recall: 0.7315 - precision: 0.5683 - 58ms/epoch - 7ms/step
Epoch 4/200
8/8 - 0s - loss: 0.6538 - accuracy: 0.6864 - recall: 0.7593 - precision: 0.6308 - 42ms/epoch - 5ms/step
Epoch 5/200
8/8 - 0s - loss: 0.6405 - accuracy: 0.6822 - recall: 0.8056 - precision: 0.6170 - 50ms/epoch - 6ms/step
Epoch 6/200
8/8 - 0s - loss: 0.6269 - accuracy: 0.6695 - recall: 0.8148 - precision: 0.6027 - 41ms/epoch - 5ms/step
Epoch 7/200
8/8 - 0s - loss: 0.6133 - accuracy: 0.6780 - recall: 0.8241 - precision: 0.6096 - 26ms/epoch - 3ms/step
Epoch 8/200
8/8 - 0s - loss: 0.5993 - accuracy: 0.6992 - recall: 0.8426 - precision: 0.6276 - 49ms/epoch - 6ms/step
Epoch 9/200
8/8 - 0s - loss: 0.5850 - accuracy: 0.7246 - recall: 0.8241 - precision: 0.6593 - 39ms/epoch - 5ms/step
Epoch 10/200
8/8 - 0s - loss: 0.5716 - accuracy: 0.7542 - recall: 0.8148 - precision: 0.6984 - 31ms/epoch - 4ms/step
Epoch 11/200
8/8 - 0s - loss: 0.5550 - accuracy: 0.7754 - recall: 0.8148 - precision: 0.7273 - 41ms/epoch - 5ms/step
Epoch 12/200
8/8 - 0s - loss: 0.5396 - accuracy: 0.7881 - recall: 0.8148 - precision: 0.7458 - 30ms/epoch - 4ms/step
Epoch 13/200
8/8 - 0s - loss: 0.5248 - accuracy: 0.8008 - recall: 0.8148 - precision: 0.7652 - 35ms/epoch - 4ms/step
Epoch 14/200
8/8 - 0s - loss: 0.5115 - accuracy: 0.8093 - recall: 0.8056 - precision: 0.7838 - 38ms/epoch - 5ms/step
Epoch 15/200
8/8 - 0s - loss: 0.4954 - accuracy: 0.8347 - recall: 0.8056 - precision: 0.8286 - 36ms/epoch - 4ms/step
Epoch 16/200
8/8 - 0s - loss: 0.4808 - accuracy: 0.8305 - recall: 0.7870 - precision: 0.8333 - 38ms/epoch - 5ms/step
Epoch 17/200
8/8 - 0s - loss: 0.4642 - accuracy: 0.8347 - recall: 0.8056 - precision: 0.8286 - 36ms/epoch - 5ms/step
Epoch 18/200
8/8 - 0s - loss: 0.4521 - accuracy: 0.8347 - recall: 0.7963 - precision: 0.8350 - 34ms/epoch - 4ms/step
Epoch 19/200
8/8 - 0s - loss: 0.4384 - accuracy: 0.8347 - recall: 0.7778 - precision: 0.8485 - 34ms/epoch - 4ms/step
Epoch 20/200
8/8 - 0s - loss: 0.4239 - accuracy: 0.8347 - recall: 0.7963 - precision: 0.8350 - 32ms/epoch - 4ms/step
Epoch 21/200
8/8 - 0s - loss: 0.4143 - accuracy: 0.8390 - recall: 0.8148 - precision: 0.8302 - 31ms/epoch - 4ms/step
Epoch 22/200
8/8 - 0s - loss: 0.4093 - accuracy: 0.8517 - recall: 0.7778 - precision: 0.8842 - 35ms/epoch - 4ms/step
Epoch 23/200
8/8 - 0s - loss: 0.4015 - accuracy: 0.8390 - recall: 0.7778 - precision: 0.8571 - 33ms/epoch - 4ms/step
Epoch 24/200
8/8 - 0s - loss: 0.3920 - accuracy: 0.8305 - recall: 0.7778 - precision: 0.8400 - 33ms/epoch - 4ms/step
Epoch 25/200
8/8 - 0s - loss: 0.3848 - accuracy: 0.8517 - recall: 0.8056 - precision: 0.8614 - 31ms/epoch - 4ms/step
Epoch 26/200
8/8 - 0s - loss: 0.3797 - accuracy: 0.8475 - recall: 0.7963 - precision: 0.8600 - 32ms/epoch - 4ms/step
Epoch 27/200
8/8 - 0s - loss: 0.3760 - accuracy: 0.8475 - recall: 0.7778 - precision: 0.8750 - 35ms/epoch - 4ms/step
Epoch 28/200
8/8 - 0s - loss: 0.3729 - accuracy: 0.8475 - recall: 0.8148 - precision: 0.8462 - 33ms/epoch - 4ms/step
Epoch 29/200
8/8 - 0s - loss: 0.3669 - accuracy: 0.8602 - recall: 0.7870 - precision: 0.8947 - 31ms/epoch - 4ms/step
Epoch 30/200
8/8 - 0s - loss: 0.3674 - accuracy: 0.8517 - recall: 0.7593 - precision: 0.9011 - 33ms/epoch - 4ms/step
Epoch 31/200
8/8 - 0s - loss: 0.3624 - accuracy: 0.8517 - recall: 0.7870 - precision: 0.8763 - 32ms/epoch - 4ms/step
Epoch 32/200
8/8 - 0s - loss: 0.3600 - accuracy: 0.8559 - recall: 0.8056 - precision: 0.8700 - 34ms/epoch - 4ms/step
Epoch 33/200
8/8 - 0s - loss: 0.3545 - accuracy: 0.8602 - recall: 0.7963 - precision: 0.8866 - 35ms/epoch - 4ms/step
Epoch 34/200
8/8 - 0s - loss: 0.3522 - accuracy: 0.8602 - recall: 0.7963 - precision: 0.8866 - 35ms/epoch - 4ms/step
Epoch 35/200
8/8 - 0s - loss: 0.3487 - accuracy: 0.8602 - recall: 0.8056 - precision: 0.8788 - 31ms/epoch - 4ms/step
Epoch 36/200
8/8 - 0s - loss: 0.3480 - accuracy: 0.8644 - recall: 0.8241 - precision: 0.8725 - 38ms/epoch - 5ms/step
Epoch 37/200
8/8 - 0s - loss: 0.3455 - accuracy: 0.8559 - recall: 0.7963 - precision: 0.8776 - 35ms/epoch - 4ms/step
Epoch 38/200
8/8 - 0s - loss: 0.3446 - accuracy: 0.8517 - recall: 0.7870 - precision: 0.8763 - 33ms/epoch - 4ms/step
Epoch 39/200
8/8 - 0s - loss: 0.3399 - accuracy: 0.8644 - recall: 0.8148 - precision: 0.8800 - 32ms/epoch - 4ms/step
Epoch 40/200
8/8 - 0s - loss: 0.3388 - accuracy: 0.8559 - recall: 0.7870 - precision: 0.8854 - 31ms/epoch - 4ms/step
Epoch 41/200
8/8 - 0s - loss: 0.3347 - accuracy: 0.8559 - recall: 0.7778 - precision: 0.8936 - 33ms/epoch - 4ms/step
Epoch 42/200
8/8 - 0s - loss: 0.3351 - accuracy: 0.8729 - recall: 0.8426 - precision: 0.8750 - 38ms/epoch - 5ms/step
Epoch 43/200
8/8 - 0s - loss: 0.3331 - accuracy: 0.8771 - recall: 0.8426 - precision: 0.8835 - 34ms/epoch - 4ms/step
Epoch 44/200
8/8 - 0s - loss: 0.3298 - accuracy: 0.8729 - recall: 0.8426 - precision: 0.8750 - 32ms/epoch - 4ms/step
Epoch 45/200
8/8 - 0s - loss: 0.3312 - accuracy: 0.8517 - recall: 0.7870 - precision: 0.8763 - 33ms/epoch - 4ms/step
Epoch 46/200
8/8 - 0s - loss: 0.3281 - accuracy: 0.8644 - recall: 0.8241 - precision: 0.8725 - 34ms/epoch - 4ms/step
Epoch 47/200
8/8 - 0s - loss: 0.3251 - accuracy: 0.8771 - recall: 0.8519 - precision: 0.8762 - 31ms/epoch - 4ms/step
Epoch 48/200
8/8 - 0s - loss: 0.3233 - accuracy: 0.8729 - recall: 0.8426 - precision: 0.8750 - 34ms/epoch - 4ms/step
Epoch 49/200
8/8 - 0s - loss: 0.3222 - accuracy: 0.8686 - recall: 0.8333 - precision: 0.8738 - 34ms/epoch - 4ms/step
Epoch 50/200
8/8 - 0s - loss: 0.3211 - accuracy: 0.8644 - recall: 0.8148 - precision: 0.8800 - 33ms/epoch - 4ms/step
Epoch 51/200
8/8 - 0s - loss: 0.3184 - accuracy: 0.8686 - recall: 0.8241 - precision: 0.8812 - 29ms/epoch - 4ms/step
Epoch 52/200
8/8 - 0s - loss: 0.3171 - accuracy: 0.8771 - recall: 0.8426 - precision: 0.8835 - 33ms/epoch - 4ms/step
Epoch 53/200
8/8 - 0s - loss: 0.3142 - accuracy: 0.8771 - recall: 0.8426 - precision: 0.8835 - 35ms/epoch - 4ms/step
Epoch 54/200
8/8 - 0s - loss: 0.3149 - accuracy: 0.8729 - recall: 0.8333 - precision: 0.8824 - 37ms/epoch - 5ms/step
Epoch 55/200
8/8 - 0s - loss: 0.3122 - accuracy: 0.8771 - recall: 0.8426 - precision: 0.8835 - 37ms/epoch - 5ms/step
Epoch 56/200
8/8 - 0s - loss: 0.3130 - accuracy: 0.8771 - recall: 0.8519 - precision: 0.8762 - 35ms/epoch - 4ms/step
Epoch 57/200
8/8 - 0s - loss: 0.3084 - accuracy: 0.8771 - recall: 0.8426 - precision: 0.8835 - 30ms/epoch - 4ms/step
Epoch 58/200
8/8 - 0s - loss: 0.3098 - accuracy: 0.8729 - recall: 0.8241 - precision: 0.8900 - 31ms/epoch - 4ms/step
Epoch 59/200
8/8 - 0s - loss: 0.3076 - accuracy: 0.8771 - recall: 0.8426 - precision: 0.8835 - 38ms/epoch - 5ms/step
Epoch 60/200
8/8 - 0s - loss: 0.3057 - accuracy: 0.8771 - recall: 0.8426 - precision: 0.8835 - 32ms/epoch - 4ms/step
Epoch 61/200
8/8 - 0s - loss: 0.3044 - accuracy: 0.8644 - recall: 0.8148 - precision: 0.8800 - 34ms/epoch - 4ms/step
Epoch 62/200
8/8 - 0s - loss: 0.3014 - accuracy: 0.8686 - recall: 0.8241 - precision: 0.8812 - 39ms/epoch - 5ms/step
Epoch 63/200
8/8 - 0s - loss: 0.3048 - accuracy: 0.8814 - recall: 0.8611 - precision: 0.8774 - 31ms/epoch - 4ms/step
Epoch 64/200
8/8 - 0s - loss: 0.3005 - accuracy: 0.8814 - recall: 0.8611 - precision: 0.8774 - 38ms/epoch - 5ms/step
Epoch 65/200
8/8 - 0s - loss: 0.3021 - accuracy: 0.8686 - recall: 0.8056 - precision: 0.8969 - 32ms/epoch - 4ms/step
Epoch 66/200
8/8 - 0s - loss: 0.2975 - accuracy: 0.8686 - recall: 0.8241 - precision: 0.8812 - 36ms/epoch - 5ms/step
Epoch 67/200
8/8 - 0s - loss: 0.2971 - accuracy: 0.8771 - recall: 0.8519 - precision: 0.8762 - 32ms/epoch - 4ms/step
Epoch 68/200
8/8 - 0s - loss: 0.2960 - accuracy: 0.8856 - recall: 0.8611 - precision: 0.8857 - 35ms/epoch - 4ms/step
Epoch 69/200
8/8 - 0s - loss: 0.2937 - accuracy: 0.8814 - recall: 0.8519 - precision: 0.8846 - 34ms/epoch - 4ms/step
Epoch 70/200
8/8 - 0s - loss: 0.2925 - accuracy: 0.8771 - recall: 0.8426 - precision: 0.8835 - 37ms/epoch - 5ms/step
Epoch 71/200

8/8 - 0s - loss: 0.2914 - accuracy: 0.8729 - recall: 0.8241 - precision: 0.8900 - 34ms/epoch - 4ms/step
Epoch 72/200
8/8 - 0s - loss: 0.2903 - accuracy: 0.8814 - recall: 0.8519 - precision: 0.8846 - 31ms/epoch - 4ms/step
Epoch 73/200
8/8 - 0s - loss: 0.2887 - accuracy: 0.8898 - recall: 0.8611 - precision: 0.8942 - 30ms/epoch - 4ms/step
Epoch 74/200
8/8 - 0s - loss: 0.2889 - accuracy: 0.8771 - recall: 0.8333 - precision: 0.8911 - 30ms/epoch - 4ms/step
Epoch 75/200
8/8 - 0s - loss: 0.2886 - accuracy: 0.8814 - recall: 0.8519 - precision: 0.8846 - 32ms/epoch - 4ms/step
Epoch 76/200
8/8 - 0s - loss: 0.2863 - accuracy: 0.8814 - recall: 0.8426 - precision: 0.8922 - 31ms/epoch - 4ms/step
Epoch 77/200
8/8 - 0s - loss: 0.2850 - accuracy: 0.8814 - recall: 0.8333 - precision: 0.9000 - 31ms/epoch - 4ms/step
Epoch 78/200
8/8 - 0s - loss: 0.2924 - accuracy: 0.8729 - recall: 0.8611 - precision: 0.8611 - 29ms/epoch - 4ms/step
Epoch 79/200
8/8 - 0s - loss: 0.2885 - accuracy: 0.8856 - recall: 0.8333 - precision: 0.9091 - 30ms/epoch - 4ms/step
Epoch 80/200
8/8 - 0s - loss: 0.2833 - accuracy: 0.8856 - recall: 0.8333 - precision: 0.9091 - 30ms/epoch - 4ms/step
Epoch 81/200
8/8 - 0s - loss: 0.2828 - accuracy: 0.8771 - recall: 0.8426 - precision: 0.8835 - 31ms/epoch - 4ms/step
Epoch 82/200
8/8 - 0s - loss: 0.2806 - accuracy: 0.8856 - recall: 0.8611 - precision: 0.8857 - 34ms/epoch - 4ms/step
Epoch 83/200
8/8 - 0s - loss: 0.2802 - accuracy: 0.8856 - recall: 0.8704 - precision: 0.8785 - 30ms/epoch - 4ms/step
Epoch 84/200
8/8 - 0s - loss: 0.2788 - accuracy: 0.8898 - recall: 0.8426 - precision: 0.9100 - 32ms/epoch - 4ms/step
Epoch 85/200
8/8 - 0s - loss: 0.2772 - accuracy: 0.8983 - recall: 0.8519 - precision: 0.9200 - 32ms/epoch - 4ms/step
Epoch 86/200
8/8 - 0s - loss: 0.2769 - accuracy: 0.8856 - recall: 0.8519 - precision: 0.8932 - 31ms/epoch - 4ms/step
Epoch 87/200
8/8 - 0s - loss: 0.2757 - accuracy: 0.8856 - recall: 0.8333 - precision: 0.9091 - 34ms/epoch - 4ms/step
Epoch 88/200
8/8 - 0s - loss: 0.2736 - accuracy: 0.8856 - recall: 0.8426 - precision: 0.9010 - 31ms/epoch - 4ms/step
Epoch 89/200
8/8 - 0s - loss: 0.2729 - accuracy: 0.8898 - recall: 0.8611 - precision: 0.8942 - 33ms/epoch - 4ms/step
Epoch 90/200
8/8 - 0s - loss: 0.2715 - accuracy: 0.8983 - recall: 0.8611 - precision: 0.9118 - 30ms/epoch - 4ms/step
Epoch 91/200
8/8 - 0s - loss: 0.2705 - accuracy: 0.8898 - recall: 0.8426 - precision: 0.9100 - 29ms/epoch - 4ms/step
Epoch 92/200
8/8 - 0s - loss: 0.2729 - accuracy: 0.8856 - recall: 0.8148 - precision: 0.9263 - 31ms/epoch - 4ms/step
Epoch 93/200
8/8 - 0s - loss: 0.2718 - accuracy: 0.8941 - recall: 0.8611 - precision: 0.9029 - 32ms/epoch - 4ms/step
Epoch 94/200
8/8 - 0s - loss: 0.2698 - accuracy: 0.8941 - recall: 0.8426 - precision: 0.9192 - 28ms/epoch - 4ms/step
Epoch 95/200
8/8 - 0s - loss: 0.2691 - accuracy: 0.8941 - recall: 0.8333 - precision: 0.9278 - 30ms/epoch - 4ms/step
Epoch 96/200
8/8 - 0s - loss: 0.2667 - accuracy: 0.8941 - recall: 0.8426 - precision: 0.9192 - 27ms/epoch - 3ms/step
Epoch 97/200
8/8 - 0s - loss: 0.2696 - accuracy: 0.8856 - recall: 0.8796 - precision: 0.8716 - 30ms/epoch - 4ms/step
Epoch 98/200
8/8 - 0s - loss: 0.2654 - accuracy: 0.8941 - recall: 0.8611 - precision: 0.9029 - 30ms/epoch - 4ms/step
Epoch 99/200
8/8 - 0s - loss: 0.2649 - accuracy: 0.8898 - recall: 0.8426 - precision: 0.9100 - 27ms/epoch - 3ms/step
Epoch 100/200
8/8 - 0s - loss: 0.2625 - accuracy: 0.8898 - recall: 0.8426 - precision: 0.9100 - 31ms/epoch - 4ms/step
Epoch 101/200
8/8 - 0s - loss: 0.2616 - accuracy: 0.8898 - recall: 0.8611 - precision: 0.8942 - 31ms/epoch - 4ms/step
Epoch 102/200
8/8 - 0s - loss: 0.2612 - accuracy: 0.8941 - recall: 0.8333 - precision: 0.9278 - 30ms/epoch - 4ms/step
Epoch 103/200
8/8 - 0s - loss: 0.2593 - accuracy: 0.8941 - recall: 0.8333 - precision: 0.9278 - 30ms/epoch - 4ms/step
Epoch 104/200
8/8 - 0s - loss: 0.2690 - accuracy: 0.8898 - recall: 0.8796 - precision: 0.8796 - 35ms/epoch - 4ms/step
Epoch 105/200
8/8 - 0s - loss: 0.2556 - accuracy: 0.9110 - recall: 0.8796 - precision: 0.9223 - 32ms/epoch - 4ms/step
Epoch 106/200
8/8 - 0s - loss: 0.2620 - accuracy: 0.8898 - recall: 0.8148 - precision: 0.9362 - 29ms/epoch - 4ms/step
Epoch 107/200
8/8 - 0s - loss: 0.2588 - accuracy: 0.8983 - recall: 0.8519 - precision: 0.9200 - 34ms/epoch - 4ms/step
Epoch 108/200
8/8 - 0s - loss: 0.2555 - accuracy: 0.9025 - recall: 0.8704 - precision: 0.9126 - 34ms/epoch - 4ms/step
Epoch 109/200
8/8 - 0s - loss: 0.2550 - accuracy: 0.8941 - recall: 0.8426 - precision: 0.9192 - 32ms/epoch - 4ms/step
Epoch 110/200
8/8 - 0s - loss: 0.2528 - accuracy: 0.8983 - recall: 0.8611 - precision: 0.9118 - 31ms/epoch - 4ms/step
Epoch 111/200
8/8 - 0s - loss: 0.2524 - accuracy: 0.8983 - recall: 0.8611 - precision: 0.9118 - 32ms/epoch - 4ms/step
Epoch 112/200
8/8 - 0s - loss: 0.2521 - accuracy: 0.8941 - recall: 0.8519 - precision: 0.9109 - 31ms/epoch - 4ms/step
Epoch 113/200
8/8 - 0s - loss: 0.2500 - accuracy: 0.8983 - recall: 0.8704 - precision: 0.9038 - 34ms/epoch - 4ms/step
Epoch 114/200
8/8 - 0s - loss: 0.2506 - accuracy: 0.8983 - recall: 0.8704 - precision: 0.9038 - 33ms/epoch - 4ms/step
Epoch 115/200
8/8 - 0s - loss: 0.2521 - accuracy: 0.9025 - recall: 0.8519 - precision: 0.9293 - 30ms/epoch - 4ms/step
Epoch 116/200
8/8 - 0s - loss: 0.2489 - accuracy: 0.8983 - recall: 0.8704 - precision: 0.9038 - 32ms/epoch - 4ms/step
Epoch 117/200
8/8 - 0s - loss: 0.2537 - accuracy: 0.8856 - recall: 0.8426 - precision: 0.9010 - 35ms/epoch - 4ms/step
Epoch 118/200
8/8 - 0s - loss: 0.2521 - accuracy: 0.8898 - recall: 0.8519 - precision: 0.9020 - 31ms/epoch - 4ms/step
Epoch 119/200
8/8 - 0s - loss: 0.2458 - accuracy: 0.9025 - recall: 0.8611 - precision: 0.9208 - 31ms/epoch - 4ms/step
Epoch 120/200
8/8 - 0s - loss: 0.2467 - accuracy: 0.8941 - recall: 0.8333 - precision: 0.9278 - 34ms/epoch - 4ms/step
Epoch 121/200
8/8 - 0s - loss: 0.2441 - accuracy: 0.9068 - recall: 0.8796 - precision: 0.9135 - 33ms/epoch - 4ms/step
Epoch 122/200
8/8 - 0s - loss: 0.2429 - accuracy: 0.9068 - recall: 0.8796 - precision: 0.9135 - 32ms/epoch - 4ms/step
Epoch 123/200
8/8 - 0s - loss: 0.2417 - accuracy: 0.8983 - recall: 0.8519 - precision: 0.9200 - 28ms/epoch - 4ms/step
Epoch 124/200
8/8 - 0s - loss: 0.2403 - accuracy: 0.9068 - recall: 0.8704 - precision: 0.9216 - 30ms/epoch - 4ms/step
Epoch 125/200
8/8 - 0s - loss: 0.2401 - accuracy: 0.9068 - recall: 0.8704 - precision: 0.9216 - 32ms/epoch - 4ms/step
Epoch 126/200
8/8 - 0s - loss: 0.2396 - accuracy: 0.9025 - recall: 0.8611 - precision: 0.9208 - 34ms/epoch - 4ms/step
Epoch 127/200
8/8 - 0s - loss: 0.2374 - accuracy: 0.9068 - recall: 0.8704 - precision: 0.9216 - 32ms/epoch - 4ms/step
Epoch 128/200
8/8 - 0s - loss: 0.2377 - accuracy: 0.9068 - recall: 0.8796 - precision: 0.9135 - 28ms/epoch - 3ms/step
Epoch 129/200
8/8 - 0s - loss: 0.2357 - accuracy: 0.9110 - recall: 0.8796 - precision: 0.9223 - 30ms/epoch - 4ms/step
Epoch 130/200
8/8 - 0s - loss: 0.2350 - accuracy: 0.9025 - recall: 0.8519 - precision: 0.9293 - 27ms/epoch - 3ms/step
Epoch 131/200
8/8 - 0s - loss: 0.2348 - accuracy: 0.9153 - recall: 0.8889 - precision: 0.9231 - 31ms/epoch - 4ms/step
Epoch 132/200
8/8 - 0s - loss: 0.2342 - accuracy: 0.9110 - recall: 0.8889 - precision: 0.9143 - 36ms/epoch - 4ms/step
Epoch 133/200
8/8 - 0s - loss: 0.2324 - accuracy: 0.9025 - recall: 0.8611 - precision: 0.9208 - 34ms/epoch - 4ms/step
Epoch 134/200
8/8 - 0s - loss: 0.2316 - accuracy: 0.9153 - recall: 0.8889 - precision: 0.9231 - 31ms/epoch - 4ms/step
Epoch 135/200
8/8 - 0s - loss: 0.2321 - accuracy: 0.8983 - recall: 0.8519 - precision: 0.9200 - 30ms/epoch - 4ms/step
Epoch 136/200
8/8 - 0s - loss: 0.2279 - accuracy: 0.9110 - recall: 0.8889 - precision: 0.9143 - 31ms/epoch - 4ms/step
Epoch 137/200
8/8 - 0s - loss: 0.2303 - accuracy: 0.9153 - recall: 0.8981 - precision: 0.9151 - 31ms/epoch - 4ms/step
Epoch 138/200
8/8 - 0s - loss: 0.2320 - accuracy: 0.9068 - recall: 0.8519 - precision: 0.9388 - 29ms/epoch - 4ms/step
Epoch 139/200
8/8 - 0s - loss: 0.2265 - accuracy: 0.9153 - recall: 0.8796 - precision: 0.9314 - 35ms/epoch - 4ms/step
Epoch 140/200
8/8 - 0s - loss: 0.2285 - accuracy: 0.9025 - recall: 0.8796 - precision: 0.9048 - 33ms/epoch - 4ms/step

Epoch 141/200
8/8 - 0s - loss: 0.2252 - accuracy: 0.9110 - recall: 0.8981 - precision: 0.9065 - 30ms/epoch - 4ms/step
Epoch 142/200
8/8 - 0s - loss: 0.2267 - accuracy: 0.9153 - recall: 0.8611 - precision: 0.9490 - 31ms/epoch - 4ms/step
Epoch 143/200
8/8 - 0s - loss: 0.2266 - accuracy: 0.9195 - recall: 0.8981 - precision: 0.9238 - 34ms/epoch - 4ms/step
Epoch 144/200
8/8 - 0s - loss: 0.2238 - accuracy: 0.9153 - recall: 0.8981 - precision: 0.9151 - 32ms/epoch - 4ms/step
Epoch 145/200
8/8 - 0s - loss: 0.2228 - accuracy: 0.9153 - recall: 0.8704 - precision: 0.9400 - 32ms/epoch - 4ms/step
Epoch 146/200
8/8 - 0s - loss: 0.2245 - accuracy: 0.9025 - recall: 0.8426 - precision: 0.9381 - 32ms/epoch - 4ms/step
Epoch 147/200
8/8 - 0s - loss: 0.2222 - accuracy: 0.9195 - recall: 0.8889 - precision: 0.9320 - 31ms/epoch - 4ms/step
Epoch 148/200
8/8 - 0s - loss: 0.2167 - accuracy: 0.9153 - recall: 0.8981 - precision: 0.9151 - 32ms/epoch - 4ms/step
Epoch 149/200
8/8 - 0s - loss: 0.2212 - accuracy: 0.9110 - recall: 0.8426 - precision: 0.9579 - 30ms/epoch - 4ms/step
Epoch 150/200
8/8 - 0s - loss: 0.2203 - accuracy: 0.9110 - recall: 0.8704 - precision: 0.9307 - 31ms/epoch - 4ms/step
Epoch 151/200
8/8 - 0s - loss: 0.2177 - accuracy: 0.9153 - recall: 0.8981 - precision: 0.9151 - 31ms/epoch - 4ms/step
Epoch 152/200
8/8 - 0s - loss: 0.2151 - accuracy: 0.9110 - recall: 0.8796 - precision: 0.9223 - 33ms/epoch - 4ms/step
Epoch 153/200
8/8 - 0s - loss: 0.2143 - accuracy: 0.9153 - recall: 0.8981 - precision: 0.9151 - 32ms/epoch - 4ms/step
Epoch 154/200
8/8 - 0s - loss: 0.2184 - accuracy: 0.9068 - recall: 0.8704 - precision: 0.9216 - 32ms/epoch - 4ms/step
Epoch 155/200
8/8 - 0s - loss: 0.2104 - accuracy: 0.9195 - recall: 0.8889 - precision: 0.9320 - 30ms/epoch - 4ms/step
Epoch 156/200
8/8 - 0s - loss: 0.2137 - accuracy: 0.9153 - recall: 0.8981 - precision: 0.9151 - 32ms/epoch - 4ms/step
Epoch 157/200
8/8 - 0s - loss: 0.2130 - accuracy: 0.9153 - recall: 0.8981 - precision: 0.9151 - 32ms/epoch - 4ms/step
Epoch 158/200
8/8 - 0s - loss: 0.2105 - accuracy: 0.9110 - recall: 0.8704 - precision: 0.9307 - 30ms/epoch - 4ms/step
Epoch 159/200
8/8 - 0s - loss: 0.2127 - accuracy: 0.9110 - recall: 0.8889 - precision: 0.9143 - 32ms/epoch - 4ms/step
Epoch 160/200
8/8 - 0s - loss: 0.2109 - accuracy: 0.9110 - recall: 0.8611 - precision: 0.9394 - 31ms/epoch - 4ms/step
Epoch 161/200
8/8 - 0s - loss: 0.2049 - accuracy: 0.9110 - recall: 0.8889 - precision: 0.9143 - 34ms/epoch - 4ms/step
Epoch 162/200
8/8 - 0s - loss: 0.2087 - accuracy: 0.9110 - recall: 0.8796 - precision: 0.9223 - 31ms/epoch - 4ms/step
Epoch 163/200
8/8 - 0s - loss: 0.2042 - accuracy: 0.9195 - recall: 0.8981 - precision: 0.9238 - 30ms/epoch - 4ms/step
Epoch 164/200
8/8 - 0s - loss: 0.2041 - accuracy: 0.9195 - recall: 0.8981 - precision: 0.9238 - 32ms/epoch - 4ms/step
Epoch 165/200
8/8 - 0s - loss: 0.2063 - accuracy: 0.9280 - recall: 0.9167 - precision: 0.9252 - 32ms/epoch - 4ms/step
Epoch 166/200
8/8 - 0s - loss: 0.2019 - accuracy: 0.9237 - recall: 0.9167 - precision: 0.9167 - 28ms/epoch - 4ms/step
Epoch 167/200
8/8 - 0s - loss: 0.2039 - accuracy: 0.9237 - recall: 0.8796 - precision: 0.9500 - 39ms/epoch - 5ms/step
Epoch 168/200
8/8 - 0s - loss: 0.2005 - accuracy: 0.9195 - recall: 0.8704 - precision: 0.9495 - 33ms/epoch - 4ms/step
Epoch 169/200
8/8 - 0s - loss: 0.2032 - accuracy: 0.9195 - recall: 0.9259 - precision: 0.9009 - 33ms/epoch - 4ms/step
Epoch 170/200
8/8 - 0s - loss: 0.2041 - accuracy: 0.9195 - recall: 0.8889 - precision: 0.9320 - 33ms/epoch - 4ms/step
Epoch 171/200
8/8 - 0s - loss: 0.1969 - accuracy: 0.9322 - recall: 0.9074 - precision: 0.9423 - 33ms/epoch - 4ms/step
Epoch 172/200
8/8 - 0s - loss: 0.1983 - accuracy: 0.9280 - recall: 0.9167 - precision: 0.9252 - 38ms/epoch - 5ms/step
Epoch 173/200
8/8 - 0s - loss: 0.1957 - accuracy: 0.9280 - recall: 0.9074 - precision: 0.9333 - 33ms/epoch - 4ms/step
Epoch 174/200
8/8 - 0s - loss: 0.1970 - accuracy: 0.9237 - recall: 0.9167 - precision: 0.9167 - 33ms/epoch - 4ms/step
Epoch 175/200
8/8 - 0s - loss: 0.1952 - accuracy: 0.9322 - recall: 0.9167 - precision: 0.9340 - 29ms/epoch - 4ms/step
Epoch 176/200
8/8 - 0s - loss: 0.1942 - accuracy: 0.9322 - recall: 0.9167 - precision: 0.9340 - 33ms/epoch - 4ms/step
Epoch 177/200
8/8 - 0s - loss: 0.1924 - accuracy: 0.9322 - recall: 0.9167 - precision: 0.9340 - 32ms/epoch - 4ms/step
Epoch 178/200
8/8 - 0s - loss: 0.1931 - accuracy: 0.9280 - recall: 0.8889 - precision: 0.9505 - 33ms/epoch - 4ms/step
Epoch 179/200
8/8 - 0s - loss: 0.1941 - accuracy: 0.9237 - recall: 0.9167 - precision: 0.9167 - 30ms/epoch - 4ms/step
Epoch 180/200
8/8 - 0s - loss: 0.1997 - accuracy: 0.9153 - recall: 0.8704 - precision: 0.9400 - 34ms/epoch - 4ms/step
Epoch 181/200
8/8 - 0s - loss: 0.1881 - accuracy: 0.9364 - recall: 0.9167 - precision: 0.9429 - 34ms/epoch - 4ms/step
Epoch 182/200
8/8 - 0s - loss: 0.1902 - accuracy: 0.9237 - recall: 0.9167 - precision: 0.9167 - 32ms/epoch - 4ms/step
Epoch 183/200
8/8 - 0s - loss: 0.1921 - accuracy: 0.9322 - recall: 0.8889 - precision: 0.9600 - 33ms/epoch - 4ms/step
Epoch 184/200
8/8 - 0s - loss: 0.1928 - accuracy: 0.9322 - recall: 0.9167 - precision: 0.9340 - 32ms/epoch - 4ms/step
Epoch 185/200
8/8 - 0s - loss: 0.1840 - accuracy: 0.9322 - recall: 0.8981 - precision: 0.9510 - 32ms/epoch - 4ms/step
Epoch 186/200
8/8 - 0s - loss: 0.1860 - accuracy: 0.9322 - recall: 0.8981 - precision: 0.9510 - 34ms/epoch - 4ms/step
Epoch 187/200
8/8 - 0s - loss: 0.1854 - accuracy: 0.9322 - recall: 0.9167 - precision: 0.9340 - 32ms/epoch - 4ms/step
Epoch 188/200
8/8 - 0s - loss: 0.1848 - accuracy: 0.9322 - recall: 0.9074 - precision: 0.9423 - 34ms/epoch - 4ms/step
Epoch 189/200
8/8 - 0s - loss: 0.1836 - accuracy: 0.9364 - recall: 0.9167 - precision: 0.9429 - 35ms/epoch - 4ms/step
Epoch 190/200
8/8 - 0s - loss: 0.1848 - accuracy: 0.9364 - recall: 0.9074 - precision: 0.9515 - 32ms/epoch - 4ms/step
Epoch 191/200
8/8 - 0s - loss: 0.1863 - accuracy: 0.9280 - recall: 0.9167 - precision: 0.9252 - 29ms/epoch - 4ms/step
Epoch 192/200
8/8 - 0s - loss: 0.1820 - accuracy: 0.9322 - recall: 0.9167 - precision: 0.9340 - 29ms/epoch - 4ms/step
Epoch 193/200
8/8 - 0s - loss: 0.1797 - accuracy: 0.9364 - recall: 0.9074 - precision: 0.9515 - 29ms/epoch - 4ms/step
Epoch 194/200
8/8 - 0s - loss: 0.1809 - accuracy: 0.9237 - recall: 0.9167 - precision: 0.9167 - 33ms/epoch - 4ms/step
Epoch 195/200
8/8 - 0s - loss: 0.1756 - accuracy: 0.9407 - recall: 0.9167 - precision: 0.9519 - 33ms/epoch - 4ms/step
Epoch 196/200
8/8 - 0s - loss: 0.1825 - accuracy: 0.9280 - recall: 0.8704 - precision: 0.9691 - 33ms/epoch - 4ms/step
Epoch 197/200
8/8 - 0s - loss: 0.1760 - accuracy: 0.9364 - recall: 0.9167 - precision: 0.9429 - 76ms/epoch - 9ms/step
Epoch 198/200
8/8 - 0s - loss: 0.1768 - accuracy: 0.9364 - recall: 0.9167 - precision: 0.9429 - 59ms/epoch - 7ms/step
Epoch 199/200
8/8 - 0s - loss: 0.1755 - accuracy: 0.9364 - recall: 0.9074 - precision: 0.9515 - 67ms/epoch - 8ms/step
Epoch 200/200
8/8 - 0s - loss: 0.1718 - accuracy: 0.9407 - recall: 0.9167 - precision: 0.9519 - 33ms/epoch - 4ms/step